#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanQA.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLCuaHangBanQA")]
	public partial class DBColorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertColor(Color instance);
    partial void UpdateColor(Color instance);
    partial void DeleteColor(Color instance);
    #endregion
		
		public DBColorDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLCuaHangBanQAConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBColorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBColorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBColorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBColorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Color> Colors
		{
			get
			{
				return this.GetTable<Color>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Color")]
	public partial class Color : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _COL_id;
		
		private string _COL_name;
		
		private string _COL_slug;
		
		private string _COL_PID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOL_idChanging(string value);
    partial void OnCOL_idChanged();
    partial void OnCOL_nameChanging(string value);
    partial void OnCOL_nameChanged();
    partial void OnCOL_slugChanging(string value);
    partial void OnCOL_slugChanged();
    partial void OnCOL_PIDChanging(string value);
    partial void OnCOL_PIDChanged();
    #endregion
		
		public Color()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string COL_id
		{
			get
			{
				return this._COL_id;
			}
			set
			{
				if ((this._COL_id != value))
				{
					this.OnCOL_idChanging(value);
					this.SendPropertyChanging();
					this._COL_id = value;
					this.SendPropertyChanged("COL_id");
					this.OnCOL_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL_name", DbType="NVarChar(200)")]
		public string COL_name
		{
			get
			{
				return this._COL_name;
			}
			set
			{
				if ((this._COL_name != value))
				{
					this.OnCOL_nameChanging(value);
					this.SendPropertyChanging();
					this._COL_name = value;
					this.SendPropertyChanged("COL_name");
					this.OnCOL_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL_slug", DbType="NVarChar(100)")]
		public string COL_slug
		{
			get
			{
				return this._COL_slug;
			}
			set
			{
				if ((this._COL_slug != value))
				{
					this.OnCOL_slugChanging(value);
					this.SendPropertyChanging();
					this._COL_slug = value;
					this.SendPropertyChanged("COL_slug");
					this.OnCOL_slugChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL_PID", DbType="VarChar(10)")]
		public string COL_PID
		{
			get
			{
				return this._COL_PID;
			}
			set
			{
				if ((this._COL_PID != value))
				{
					this.OnCOL_PIDChanging(value);
					this.SendPropertyChanging();
					this._COL_PID = value;
					this.SendPropertyChanged("COL_PID");
					this.OnCOL_PIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
