<?xml version="1.0" encoding="utf-8"?><Database Name="QLCuaHangBanQA" Class="DBSizeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-NHIKDDQ;Initial Catalog=QLCuaHangBanQA;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLCuaHangBanQAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Size" Member="Sizes">
    <Type Name="Size">
      <Column Name="S_id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="S_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="S_PID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>